### ISSUE TITLE
tag attribute istifadəsi

### ISSUE THREAD

**Issue by samirkarimov** [aytajquseynova/ProgramtechFoundationProject#1]
https://github.com/aytajquseynova/ProgramtechFoundationProject/blob/13c9e5bebefc94bd267bb227f2035b7dd6b123a0/htmldesehifeilkhefte/week1.html/index.html#L70

attributelar arasında ; işarəsi qoymaq səhvdir. Zəhmət olmasa [bu](https://www.w3schools.com/html/html_attributes.asp) qaynaqdan attributelar haqqında araşdırma edin

**Comment by aytajquseynova** [comment]
sehvimi duzeltdim

**Comment by aytajquseynova** [comment]
> https://github.com/aytajquseynova/ProgramtechFoundationProject/blob/13c9e5bebefc94bd267bb227f2035b7dd6b123a0/htmldesehifeilkhefte/week1.html/index.html#L70
> 
> attributelar arasında ; işarəsi qoymaq səhvdir. Zəhmət olmasa [bu](https://www.w3schools.com/html/html_attributes.asp) qaynaqdan attributelar haqqında araşdırma edin

sehvimi duzeltdim
